import { v4 as uuid } from "uuid";
import { AF1, AF2, AF3, AF4, RUN1, RUN2, RUN3, RUN4, SB1, SB2, SB3, SB4 } from "../../assets/index";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
	{
		_id: uuid(),
		title: "Air Zoom 1",
		company: "Nike",
		price: "8999",
		categoryName: "Running",
		img: RUN1,
		inStock: true,
	},
	{
		_id: uuid(),
		title: "Air Zoom 2",
		company: "Nike",
		price: "10499",
		categoryName: "Running",
		img: RUN2,
		inStock: true,
	},
	{
		_id: uuid(),
		title: "Air Zoom 3",
		company: "Nike",
		price: "9999",
		categoryName: "Running",
		img: RUN3,
		inStock: false,
	},
	{
		_id: uuid(),
		title: "Air Zoom 4",
		company: "Nike",
		price: "14999",
		categoryName: "Running",
		img: RUN4,
		inStock: true,
	},
	{
		_id: uuid(),
		title: "Air Force 1 '07",
		company: "Nike",
		price: "7899",
		categoryName: "Air Force 1",
		img: AF1,
		inStock: true,
	},
	{
		_id: uuid(),
		title: "Air Force 1 High",
		company: "Nike",
		price: "8499",
		categoryName: "Air Force 1",
		img: AF2,
		inStock: false,
	},
	{
		_id: uuid(),
		title: "Air Force 1 Crater",
		company: "Nike",
		price: "9499",
		categoryName: "Air Force 1",
		img: AF3,
		inStock: true,
	},
	{
		_id: uuid(),
		title: "Air Force 1 Luxe",
		company: "Nike",
		price: "11999",
		categoryName: "Air Force 1",
		img: AF4,
		inStock: true,
	},
	{
		_id: uuid(),
		title: "Nike SB 1",
		company: "Nike",
		price: "7899",
		categoryName: "Skateboarding",
		img: SB1,
		inStock: true,
	},
	{
		_id: uuid(),
		title: "Nike SB 2",
		company: "Nike",
		price: "8499",
		categoryName: "Skateboarding",
		img: SB2,
		inStock: true,
	},
	{
		_id: uuid(),
		title: "Nike SB 3",
		company: "Nike",
		price: "9499",
		categoryName: "Skateboarding",
		img: SB3,
		inStock: false,
	},
	{
		_id: uuid(),
		title: "Nike SB 4",
		company: "Nike",
		price: "11999",
		categoryName: "Skateboarding",
		img: SB4,
		inStock: false,
	},
];
